In [18]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'3.0.3'

In [6]:
df=pd.read_csv("E:\MachineLearning\Data\DataTalksClub-Data\car_fuel_efficiency_2026.csv")

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\E C\AppData\Local\Temp\ipykernel_15412\1629519452.py:1: SyntaxWarning: invalid escape sequence '\M'
  df=pd.read_csv("E:\MachineLearning\Data\DataTalksClub-Data\car_fuel_efficiency_2026.csv")

In [7]:
df.shape

(10000, 11)

In [8]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [13]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [20]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [16]:
df.isna().sum().sort_values(ascending=False)

horsepower             877
acceleration           264
model_year               0
fuel_type                0
origin                   0
drivetrain               0
num_doors                0
num_cylinders            0
engine_displacement      0
vehicle_weight           0
fuel_efficiency_mpg      0
dtype: int64

In [17]:
df['fuel_efficiency_mpg'].sort_values(ascending=False).head(1)

6354    41.2
Name: fuel_efficiency_mpg, dtype: float64

In [21]:
df[df['origin']=='Asia	']['fuel_efficiency_mpg'].max()

nan

In [22]:
df['horsepower'].median()

np.float64(254.0)

In [23]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [29]:
df['horsepower']=df['horsepower'].fillna(df['horsepower'].mode()[0])

In [32]:
df['horsepower'].median()

np.float64(252.0)

In [33]:
df.isna().sum().sort_values(ascending=False)

acceleration           264
origin                   0
model_year               0
fuel_type                0
drivetrain               0
engine_displacement      0
num_doors                0
num_cylinders            0
horsepower               0
vehicle_weight           0
fuel_efficiency_mpg      0
dtype: int64

In [35]:
X=df[df["origin"] == "Asia"][['vehicle_weight','model_year']].head(7)

In [36]:
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [37]:
XTX=X.T @ X

In [38]:
XTX_inv=np.linalg.inv(XTX)

In [39]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [40]:
w=XTX_inv @ X.T @ y

In [41]:
print("X =", X)
print("XTX =", XTX)
print("w =", w)
print("Sum of w =", w.sum())

X =     vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019
XTX =                 vehicle_weight  model_year
vehicle_weight       131950500    60750580
model_year            60750580    28041424
w = 0    0.136448
1    0.232749
dtype: float64
Sum of w = 0.3691969690492549